name: Update KernelSU
on: 
  workflow_dispatch:
permissions: write-all
jobs: 
  check-update:
    runs-on: ubuntu-latest
    steps:          
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y curl jq bash
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          repository: uwu-gl/kernel_oneplus_sdm845_drivers_kernelsu
          ref: main
      
      - name: Check remote release
        run: |
          echo "kernelsu_release=`curl https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r .tag_name`" >> $GITHUB_ENV
          echo "local_release=$(cat ksu_version.txt)" >> $GITHUB_ENV
      
      - name: Update    
        if: ${{ env.kernelsu_release }} != ${{ env.local_release }}
        run: |
          bash
          git clone https://github.com/tiann/KernelSU remote && cd remote
          version_ksu=$[$(git rev-list --count HEAD)+10200]
          cd - 
          rm -rf remote
          sed -i "19,30c ccflags-y += -DKSU_VERSION=$version_ksu" ./Makefile
          echo "${{ env.kernelsu_release }}" > ksu_version.txt
          echo "### Diffs" && git diff && echo "### End of diffs"
          git add . && git commit -sm "drivers: kernelsu: Bump version to $version_ksu (${{ env.kernelsu_release }})"
          git push
      
      - name: Repository Dispatch
        if: ${{ env.kernelsu_release }} != ${{ env.local_release }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN }}
          repository: uwu-gl/kernel_oneplus_sdm845
          event-type: ksu_merge_update
