name: Update KernelSU
on: 
  workflow_call:
  workflow_dispatch:
jobs: 
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          repository: uwu-gl/kernel_oneplus_sdm845_drivers_kernelsu
          ref: main-wip
          
      - name: Install common package
        run: |
          sudo apt update
          sudo apt install -y curl jq
          
      - name: Check remote release
        run: |
          kernelsu_release=`curl https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r .tag_name`
          local_release=$(cat ksu_version.txt)
          echo $kernelsu_release
          echo $local_release
          echo kernelsu_release=$kernelsu_release >> $GITHUB_ENV
          echo local_release=$local_release >> $GITHUB_ENV

      - name: Set up environment
        if: kernelsu_release != local_release
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Update
        if: kernelsu_release != local_release
        run: |
          git clone https://github.com/tiann/KernelSU ~/remote
          git clone https://github.com/uwu-gl/kernel_oneplus_sdm845_drivers_kernelsu ~/staging -b main-wip
          cd ~/staging && rm -rf *
          cp ~/remote/kernel/* .
          rm -f setup.sh
          touch ksu_version.txt 
          echo "${{ needs.check_kernelsu_update.outputs.kernelsu_release }}" > ksu_version.txt 
          echo "### Diffs" && git diff && echo "### End of diffs"
          git add . && git commit -sm "drivers: kernelsu: Bump version to ${{ needs.check_kernelsu_update.outputs.kernelsu_release }}"
          git push
          
        
        
