name: Update KernelSU
on: 
  workflow_call:
  workflow_dispatch:
jobs: 
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          repository: uwu-gl/kernel_oneplus_sdm845_drivers_kernelsu
          ref: main-wip
          
      - name: Install common package
        run: |
          sudo apt update
          sudo apt install -y curl jq bash
          
      - name: Check remote release
        run: |
          echo "kernelsu_release=`curl https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r .tag_name`" >> $GITHUB_ENV
          echo "local_release=$(cat ksu_version.txt)" >> $GITHUB_ENV
        
      - name: Update
        if: ${{ env.kernelsu_release }} != ${{ env.local_release }}
        run: |
          bash
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git clone https://github.com/tiann/KernelSU ~/remote && cd ~/remote
          echo "KSU_VERSION=$[$(git rev-list --count HEAD)+10200]" >> $GITHUB_ENV
          git clone https://github.com/uwu-gl/kernel_oneplus_sdm845_drivers_kernelsu ~/staging -b main-wip
          cd ~/staging && rm -rf *
          cp -r ~/remote/kernel/* .
          rm -f setup.sh ksu_version.txt
          sed -i '19,30c ccflags-y += -DKSU_VERSION=${{ env.KSU_VERSION }}' ./Makefile
          echo "### Diffs" && git diff && echo "### End of diffs"
          git add . && git commit -sm "drivers: kernelsu: Bump version to ${{ env.KSU_VERSION }} (${{ env.kernelsu_release }})"
          git push
          
        
        
